title: Emily's Computer Science Blog
author: Emily Young, github - emsyoungg
email: emilyoung278@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about Emily trying to improve coding by doing projects whilst getting through computer science Alevel.

# social links
twitter_username: Emsyoungg # DO NOT include the @ character, or else the build will fail!
github_username:  emsyoungg # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
